resources:
- service.yaml

## for OpenShift 4.6+
- versions/batch-v1beta1-v1-cronjob_admissionregistration.k8s.io-v1-mutatingwebhookconfiguration.yaml

## for OpenShift 3.x
# - versions/batch-v1beta1-cronjob_admissionregistration.k8s.io-v1beta1-mutatingwebhookconfiguration.yaml
# - versions/batch-v2alpha1-cronjob_admissionregistration.k8s.io-v1beta1-mutatingwebhookconfiguration.yaml

configurations:
- kustomizeconfig.yaml